export const CLI_COMMANDS = {
    UP: 'up',
    CHANGE_DIR: 'cd',
    LIST: 'ls',
    READ: 'cat',
    CREATE: 'add',
    RENAME: 'rn',
    COPY: 'cp',
    MOVE: 'mv',
    DELETE: 'rm',
    EOL: 'os --EOL',
    CPUS: 'os --cpus',
    HOMEDIR: 'os --homedir',
    SYS_USER: 'os --username',
    ARCH: 'os --architecture',
    HASH: 'hash',
    COMPRESS: 'compress',
    DECOMPRESS: 'decompress',
    EXIT: '.exit',
};